const BASE_URL = 'https://api.spotify.com/v1';

async function spotifyFetch(path: string, token: string, options?: RequestInit) {
  const res = await fetch(`${BASE_URL}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      ...(options?.headers ?? {}),
    },
  });
  if (!res.ok) throw new Error(`Spotify ${path} failed: ${res.status}`);
  if (res.status === 204) return {};
  return res.json();
}

// ─── Existing ────────────────────────────────────────────────────────────────

export const getTopArtists = (token: string) =>
  spotifyFetch('/me/top/artists?limit=10&time_range=medium_term', token);

export const getTopTracks = (token: string) =>
  spotifyFetch('/me/top/tracks?limit=10&time_range=medium_term', token);

export async function searchTracks(token: string, query: string, limit = 10) {
  const encoded = encodeURIComponent(query);
  return spotifyFetch(`/search?q=${encoded}&type=track&limit=${limit}`, token);
}

// ─── User profile ─────────────────────────────────────────────────────────────

export async function getUserProfile(token: string): Promise<{ id: string; display_name: string }> {
  return spotifyFetch('/me', token);
}

// ─── Mood search queries ──────────────────────────────────────────────────────
// Spotify deprecated /recommendations in Nov 2024.
// We use multiple targeted search queries per mood and merge results instead.

const MOOD_QUERIES: Record<string, string[]> = {
  happy: [
    'genre:pop mood:happy upbeat feel good',
    'genre:dance energetic positive vibes',
    'happy pop hits',
    'feel good summer songs',
    'upbeat indie pop',
  ],
  neutral: [
    'genre:indie chill easy listening',
    'lo-fi chill study beats',
    'mellow indie pop',
    'background chill music',
    'acoustic soft pop',
  ],
  stressed: [
    'genre:ambient calming relaxing',
    'stress relief calm meditation music',
    'peaceful acoustic chill',
    'gentle piano relax',
    'lo-fi calming focus',
  ],
  angry: [
    'genre:soul calming soothing R&B',
    'acoustic calm mellow',
    'peaceful indie folk',
    'soft chill vibes relax',
    'gentle acoustic singer songwriter',
  ],
  sad: [
    'genre:indie sad melancholy',
    'sad songs heartbreak indie',
    'melancholic singer songwriter',
    'emotional ballads',
    'rainy day sad playlist',
  ],
  sleepy: [
    'genre:ambient sleep music',
    'gentle piano sleep relaxing',
    'classical slow peaceful',
    'sleep lo-fi soft',
    'ambient drone calm',
  ],
};

export type SpotifyTrack = {
  id:      string;
  uri:     string;
  name:    string;
  artists: { name: string }[];
  album:   { name: string; images: { url: string }[] };
  external_urls: { spotify: string };
};

export async function getMoodRecommendations(
  token: string,
  mood: string,
  limit = 20,
): Promise<{ tracks: SpotifyTrack[] }> {
  const queries = MOOD_QUERIES[mood] ?? MOOD_QUERIES['neutral'];

  // Run 2-3 searches in parallel, each returning limit/2 tracks
  const perQuery = Math.ceil(limit / 2);
  const selectedQueries = queries.slice(0, 2);

  const results = await Promise.allSettled(
    selectedQueries.map(q => searchTracks(token, q, perQuery)),
  );

  const seen = new Set<string>();
  const tracks: SpotifyTrack[] = [];

  for (const result of results) {
    if (result.status !== 'fulfilled') continue;
    const items: SpotifyTrack[] = result.value?.tracks?.items ?? [];
    for (const track of items) {
      if (!seen.has(track.id) && tracks.length < limit) {
        seen.add(track.id);
        tracks.push(track);
      }
    }
  }

  return { tracks };
}

// ─── Playlist creation ────────────────────────────────────────────────────────

export async function createPlaylist(
  token: string,
  userId: string,
  name: string,
  description = '',
): Promise<{ id: string; external_urls: { spotify: string } }> {
  return spotifyFetch(`/users/${userId}/playlists`, token, {
    method: 'POST',
    body: JSON.stringify({ name, description, public: false }),
  });
}

export async function addTracksToPlaylist(
  token: string,
  playlistId: string,
  uris: string[],
): Promise<void> {
  await spotifyFetch(`/playlists/${playlistId}/tracks`, token, {
    method: 'POST',
    body: JSON.stringify({ uris }),
  });
}

// ─── Full generate flow ───────────────────────────────────────────────────────

export async function generateMoodPlaylist(
  token: string,
  mood: string,
  moodEmoji: string,
): Promise<{ playlistUrl: string; trackCount: number }> {
  const [profile, recResult] = await Promise.all([
    getUserProfile(token),
    getMoodRecommendations(token, mood, 20),
  ]);

  const tracks = recResult.tracks;
  if (tracks.length === 0) throw new Error('No tracks found for this mood');

  const date    = new Date().toLocaleDateString('en-CA');
  const name    = `${moodEmoji} ${mood.charAt(0).toUpperCase() + mood.slice(1)} Vibes — ${date}`;
  const desc    = `Auto-generated by Commubu for your ${mood} mood on ${date}`;

  const playlist = await createPlaylist(token, profile.id, name, desc);
  const uris     = tracks.map(t => t.uri);
  await addTracksToPlaylist(token, playlist.id, uris);

  return {
    playlistUrl: playlist.external_urls.spotify,
    trackCount:  tracks.length,
  };
}